services:
  react-app:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
    command: "npm run dev"
    networks:
      - dev_network

networks:
  dev_network:
    external: true
    name: dev_network
